---
title: "Example delay estimation from line list data"
description: "Example delay estimation of delay between symptom onset and hospital admission and death"
---

## Setup
```{r}
library(dplyr)
library(ggplot2)
```

## Loading the data
```{r}
ll_clean <- readr::read_csv(here::here("data-raw", "clean_linelist.csv"))
ll_missing <- readr::read_csv(here::here("data-raw", "missing_linelist.csv"))
```

```{r}
ll_imputed <- ll_missing |> mutate(date_onset = date_onset_miss_rd_impute_100)
```

Merging all line lists into one df
```{r}
ll_all <- bind_rows(list(clean = ll_clean, imputed = ll_imputed), .id = "ll_source")
```

```{r}
delay_admission <- ll_all |>
  filter(!is.na(date_onset), !is.na(date_admission)) |>
  mutate(delay = date_admission - date_onset)
```

```{r}
delay_death <- ll_all |>
  filter(!is.na(date_onset), outcome == "died", !is.na(date_outcome)) |>
  mutate(delay = date_outcome - date_onset)
```

## Empirical plots

### Onset to admission
```{r}
delay_admission |>
  group_by(ll_source, delay) |>
  summarise(n = n()) |>
  ungroup() |> 
  ggplot() +
  geom_col(aes(x = delay, y = n)) +
  facet_wrap(~ll_source, ncol = 1) +
  labs(x = "Delay (days)", y = "Number of cases") +
  ggtitle("Delay between date of onset and date of admission") +
  theme_minimal()
```
### Onset to death
```{r}
delay_death |>
  group_by(ll_source, delay) |>
  summarise(n = n()) |>
  ungroup() |> 
  ggplot(aes(x = delay, y = n)) +
  geom_col() +
  facet_wrap(~ll_source, ncol = 1) +
  labs(x = "Delay (days)", y = "Number of cases") +
  ggtitle("Delay between date of onset and date of death") +
  theme_minimal()
```

## Estimation via primarycensored
```{r}
library(primarycensored)
library(cmdstanr)
```

```{r}
pcd_model <- pcd_cmdstan_model(cpp_options = list(stan_threads = FALSE))
```

```{r}
get_dist_estimates_pcd <- function(delay_data) {
  pcd_data <- pcd_as_stan_data(
  delay_data,
  delay = "observed_delay",
  delay_upper = "observed_delay_upper",
  relative_obs_time = "D",
  pwindow = "pwindow",
  dist_id = pcd_stan_dist_id("lognormal", "delay"),
  primary_id = pcd_stan_dist_id("uniform", "primary"),
  param_bounds = list(lower = c(-Inf, 0), upper = c(Inf, Inf)),
  primary_param_bounds = list(lower = numeric(0), upper = numeric(0)),
  priors = list(location = c(1, 0.5), scale = c(1, 0.5)),
  primary_priors = list(location = numeric(0), scale = numeric(0)),
  use_reduce_sum = FALSE # use within chain parallelisation
)

pcd_fit <- pcd_model$sample(
  data = pcd_data,
  chains = 4,
  parallel_chains = 2, # Run 2 chains in parallel
  threads_per_chain = 2, # Use 2 cores per chain
  refresh = ifelse(interactive(), 50, 0),
  show_messages = interactive()
)

return(pcd_fit)
}
```

```{r}
get_delay_counts <- function(df, max_delay) {
  df |>
  filter(delay >= 0) |> 
  mutate(delay = as.numeric(delay)) |>
  group_by(delay) |>
  summarise(n = n()) |>
  ungroup() |> 
  transmute(
    ll_source = unique(df$ll_source),
    observed_delay = delay,
    observed_delay_upper = delay + 1,
    pwindow = 1,
    D = max_delay,
    n = n)
}
```

```{r}
delay_admission_counts <- delay_admission |> 
  group_split(ll_source) |> 
  lapply(FUN = get_delay_counts, max_delay = 30)

names(delay_admission_counts) <- sapply(delay_admission_counts, function(x) x$ll_source[1])

delay_admission_pcd <- delay_admission_counts |> 
  lapply(FUN = get_dist_estimates_pcd)

delay_admission_estimates <- delay_admission_pcd |> 
  lapply(FUN = function(fit) {
  fit$summary(c("params[1]", "params[2]")) |> 
    mutate(variable = c("meanlog", "sdlog"))
})
```

```{r}
delay_death_counts <- delay_death |> 
  group_split(ll_source) |> 
  lapply(FUN = get_delay_counts, max_delay = 90)

names(delay_death_counts) <- sapply(delay_death_counts, function(x) x$ll_source[1])

delay_death_pcd <- delay_death_counts |> 
  lapply(FUN = get_dist_estimates_pcd)

delay_death_estimates <- delay_death_pcd |> 
  lapply(FUN = function(fit) {
  fit$summary(c("params[1]", "params[2]")) |> 
    mutate(variable = c("meanlog", "sdlog"))
})
```

## Result plots

### Onset to admission
```{r}
delay_admission_estimates |> 
  bind_rows(.id = "ll_source") |> 
  ggplot(aes(y = ll_source)) +
  geom_point(aes(x = mean)) +
  geom_errorbar(aes(xmin = q5, xmax = q95), width = 0.2) +
  facet_wrap(~variable, ncol = 1, scales = "free_x") +
  labs(y = "Parameter", x = "Value") +
  ggtitle("Delay between date of onset and date of admission") +
  theme_bw()
```
Density
```{r}
# simulate draws from estimated lognormal distribution
ndraws <- 10000
admission_dist_draws <- delay_admission_estimates |> lapply(FUN = function(estimates) data.frame(delay = rlnorm(n = ndraws,
       meanlog = estimates |> filter(variable == "meanlog") |> pull(mean),
       sdlog = estimates |> filter(variable == "sdlog") |>  pull(mean)
  ))) |> bind_rows(.id = "ll_source")
```

```{r}
delay_admission_stats <- admission_dist_draws |>
  group_by(ll_source) |>
  summarise(mean_delay = mean(delay, na.rm = TRUE),
            median_delay = median(delay, na.rm = TRUE),
            sd_delay = sd(delay, na.rm = TRUE))

admission_dist_draws |>
  ggplot() +
  geom_density(aes(x=delay)) +
  geom_vline(data = delay_admission_stats, aes(xintercept = mean_delay), linetype = "dashed", color = "red") +
  geom_vline(data = delay_admission_stats, aes(xintercept = median_delay), linetype = "dashed", color = "blue") +
  facet_wrap(~ll_source, ncol = 1) +
  labs(x = "Delay (days)", y = "Number of cases") +
  ggtitle("Delay between date of onset and date of admission") +
  theme_minimal()
```

### Onset to death

```{r}
delay_death_estimates |> 
  bind_rows(.id = "ll_source") |> 
  ggplot(aes(y = ll_source)) +
  geom_point(aes(x = mean)) +
  geom_errorbar(aes(xmin = q5, xmax = q95), width = 0.2) +
  facet_wrap(~variable, ncol = 1, scales = "free_x") +
  labs(y = "Parameter", x = "Value") +
  ggtitle("Delay between date of onset and date of death") +
  theme_bw()
```

```{r}
# simulate draws from estimated lognormal distribution
ndraws <- 10000
death_dist_draws <- delay_death_estimates |> lapply(FUN = function(estimates) data.frame(delay = rlnorm(n = ndraws,
       meanlog = estimates |> filter(variable == "meanlog") |> pull(mean),
       sdlog = estimates |> filter(variable == "sdlog") |>  pull(mean)
  ))) |> bind_rows(.id = "ll_source")
```

```{r}
delay_death_stats <- death_dist_draws |>
  group_by(ll_source) |>
  summarise(mean_delay = mean(delay, na.rm = TRUE),
            median_delay = median(delay, na.rm = TRUE),
            sd_delay = sd(delay, na.rm = TRUE))

death_dist_draws |>
  ggplot() +
  geom_density(aes(x=delay)) +
  geom_vline(data = delay_death_stats, aes(xintercept = mean_delay), linetype = "dashed", color = "red") +
  geom_vline(data = delay_death_stats, aes(xintercept = median_delay), linetype = "dashed", color = "blue") +
  facet_wrap(~ll_source, ncol = 1) +
  labs(x = "Delay (days)", y = "Number of cases") +
  ggtitle("Delay between date of onset and date of death") +
  theme_minimal()
```

